### ISSUE TITLE
Bug FeaturePartsSelectOnRect

### ISSUE THREAD

**Issue by tmctono** [mtonosaki/Tono#21]
I have found bugs below in the new feature  FeaturePartsSelectOnRect.

1. Flush a selecting box when I just click after use this feature.
2. When I use Toolbox (or UWP control), this feature makes a selecting box unexpectedly.

**Comment by mtonosaki** [comment]
Fixed. Also you can use updated NuGet package Tono.Gui.Uwp 1.0.16
